development:
  secret_key_base: f62879e0bd1eb5e56171df88029fefdc5106496745cefd7eadffe55fce76da5f88fcd20494971ea4b52fe3ee8bc48d4183ed2140f876a90fd0295a9961a56999
  aws_access_key_id: AKIA
  aws_secret_access_key: 12345
  neo4j_session_path: http://localhost:7474

test:
  secret_key_base: e3aed5c1aecf8a92d7499384395dde8ef56567d6c7350779bffb6d73876b8ac477ca28eb018eaa191b634acdb89c4c7d17728dced4887c0b6913c18d4bda10c5
  aws_access_key_id: AKIA
  aws_secret_access_key: 12345
  neo4j_session_path: http://localhost:7474

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  redis_url: <%= ENV["HEROKU_REDIS_PURPLE_URL"] %>
  neo4j_session_path: <%= ENV["GRAPHENEDB_URL"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  cloudfront_distro_id: <%= ENV["AWS_CLOUDFRONT_DISTRO_ID"] %>
